/*
 * ECS API
 *
 * ECS API
 *
 * API version: 0.0.1
 * Contact: eiffel.zhou@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Task struct {
	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	Image string `json:"image,omitempty"`

	Cpu string `json:"cpu,omitempty"`

	Memory string `json:"memory,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	// task status
	Status string `json:"status,omitempty"`
}
